### ISSUE TITLE
License statement

### ISSUE THREAD

**Issue by fabaff** [azur1s/octofetch#11]
Currently there is no license statement. Could you please add a `LICENSE` file that contains the license text.

Thanks.

**Comment by azur1s** [comment]
I added MIT License on the lastest commit, I hope that is the right one to choose

**Comment by azur1s** [comment]
I'm closing this because I added the license on this [commit,](https://github.com/azur1s/octofetch/commit/71a5af1e8e53716f29e59cf538c209c107db619e) If you have more issue then let me know, I'm glad to help :D

**Comment by fabaff** [comment]
Thank you. It allows to set the license for distribution packaging, e.g., https://github.com/NixOS/nixpkgs/pull/143831
